---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "exomiser"
description: Exomiser annotates, filters and prioritizes likely causative variants
keywords:
  - variant prioritization
  - disease phenotype
  - genomics
tools:
  - "exomiser":
      description: "Exomiser - A Tool to Annotate and Prioritize Exome Variants"
      homepage: "https://github.com/exomiser/Exomiser"
      documentation: "https://exomiser.readthedocs.io/en/latest/"
      tool_dev_url: "https://github.com/exomiser/Exomiser"
      doi: "10.1038/nprot.2015.124"
      licence: ['AGPL v3']
      identifier: biotools:exomiser

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'sample1', sequencing_type:'WES' ]
    - vcf_file:
        type: file
        description: vcf file containing variants to be analyzed (e.g. "sample1.vcf.gz")
        pattern: "*.{vcf.gz,vcf}"
    - index_file:
        type: file
        description: index file of the vcf file (e.g. "sample1.vcf.gz.tbi")
        pattern: "*.{vcf.gz.tbi,vcf.tbi}"
    - pheno_file:
        type: file
        description: Phenopacket file containing clinical information relevant to the exomiser analysis (e.g. "sample1.pheno.json")
        pattern: "*.{yaml,yml,json}"
    - analysis_file:
        type: file
        description: File containing the exomiser analysis configuration (e.g. "exomiser_analysis.yml")
        pattern: "*.{yaml,yml}"

  -  - data_dir:
        type: directory
        description: Path to the directory containing exomiser reference data (e.g. "data-test/reference/exomiser")

  -  - exomiser_genome:
        type: string
        description: The genome assembly to use with exomiser ("hg19" or "hg38")

  - - exomiser_data_version:
        type: string
        description: The version of the Exomiser reference data to be used. (e.g. "2402")

  - - local_frequency_path:
        type: file
        description: The path to the local frequency file to use (e.g. "local_frequency_test_hg38.tsv.gz")
    - local_frequency_index_path:
        type: file
        description: The path to the index of the local frequency file (e.g. "local_frequency_test_hg38.tsv.gz.tbi")

  - - remm_version:
        type: string
        description: The version of the REMM pathogenicity data source to use (e.g. "0.3.1.post1")
    - remm_file_name:
        type: string
        description: The name of the REMM reference file to use (e.g. "ReMM.v0.3.1.post1.hg38.tsv.gz")

  - - cadd_version:
        type: string
        description: The version of the CADD pathongenicity data source to use (e.g. "1.7")
    - cadd_snv_file_name:
        type: string
        description: The name of the CADD SNV reference file to use (e.g. "whole_genome_SNVs.tsv.gz")
    - cadd_indel_file_name:
        type: string
        description: The name of the CADD INDEL reference file to use (e.g. "gnomad.genomes.r4.0.indel.tsv.gz")


output:
  - vcf:
      - meta:
          type: map
          description: |
            Groovy Map containing family information
            e.g. [ id:'family1', sequencing_type:'WES' ]
      - "*.vcf.gz":
          type: file
          description: exomiser output vcf file
          pattern: "*.{vcf.gz}"

  - tbi:
      - meta:
          type: map
          description: |
            Groovy Map containing family information
            e.g. [ id:'family1', sequencing_type:'WES' ]
      - "*.vcf.gz.tbi":
          type: file
          description: index of exomiser output vcf file
          pattern: "*.{vcf.gz.tbi}"
  - html:
      - meta:
          type: map
          description: |
            Groovy Map containing family information
            e.g. [ id:'family1', sequencing_type:'WES' ]
      - "*.html":
          type: file
          description: exomiser output html file
          pattern: "*.{html}"

  - json:
      - meta:
          type: map
          description: |
            Groovy Map containing family information
            e.g. [ id:'family1', sequencing_type:'WES' ]
      - "*.json":
          type: file
          description: exomiser output json file
          pattern: "*.{json}"

  - genetsv:
      - meta:
          type: map
          description: |
            Groovy Map containing family information
            e.g. [ id:'family1', sequencing_type:'WES' ]
      - "*.genes.tsv":
          type: file
          description: exomiser output genes.tsv file
          pattern: "*.{genes.tsv}"

  - variantstsv:
      - meta:
          type: map
          description: |
            Groovy Map containing family information
            e.g. [ id:'family1', sequencing_type:'WES' ]
      - "*.variants.tsv":
          type: file
          description: exomiser output variants.tsv file
          pattern: "*.{variants.tsv}"

  - versions:
      - "versions.yml":
          type: file
          description: File containing software versions
          pattern: "versions.yml"

authors:
  - "@ferlab"
maintainers:
  - "@ferlab"
