repository_type: pipeline

nf_core_version: 3.2.0

lint:
  files_unchanged:
    - .github/CONTRIBUTING.md
    - .github/CONTRIBUTING.md
    - assets/sendmail_template.txt
    - .prettierignore
    - .prettierignore
    - .prettierignore
    - .prettierignore
    - .github/CONTRIBUTING.md
    - .github/CONTRIBUTING.md
    - assets/sendmail_template.txt
    - .prettierignore
    - .prettierignore
    - .prettierignore
    - .prettierignore
    - CODE_OF_CONDUCT.md
    - assets/nf-core-cnv-post-processing_logo_light.png
    - docs/images/nf-core-cnv-post-processing_logo_light.png
    - docs/images/nf-core-cnv-post-processing_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/email_template.txt
    - docs/README.md
  nextflow_config:
    - manifest.name
    - manifest.homePage
    - validation.help.beforeText
    - validation.help.afterText
    - validation.summary.beforeText
    - validation.summary.afterText
  multiqc_config: false
  files_exist:
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - assets/multiqc_config.yml
    - assets/email_template.html
    - assets/sendmail_template.txt
    - assets/email_template.txt
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - assets/multiqc_config.yml
    - assets/email_template.html
    - assets/sendmail_template.txt
    - assets/email_template.txt
    - CODE_OF_CONDUCT.md
    - assets/nf-core-cnv-post-processing_logo_light.png
    - docs/images/nf-core-cnv-post-processing_logo_light.png
    - docs/images/nf-core-cnv-post-processing_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
  readme:
    - nextflow_badge

template:
  org: Ferlab-Ste-Justine
  name: cnv-post-processing
  description: Nextflow pipeline dedicated to the post-processing of Copy Number Variants
    (CNVs).
  author: "Lysiane Bouchard, Georgette Femerling, F\xE9lix-Antoine Le Sieur, David\
    \ Morais"
  version: 1.0.0dev
  force: true
  outdir: .
  skip_features:
    - igenomes
    - github_badges
    - gitpod
    - codespaces
    - multiqc
    - fastqc
    - email
    - adaptivecard
    - slackreport
    - seqera_platform
    - rocrate
    - vscode
  is_nfcore: false
