repository_type: pipeline

nf_core_version: 3.2.0

lint:
  files_unchanged:
    - docs/README.md
    - .github/CONTRIBUTING.md
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/workflows/linting.yml
    - .prettierignore
    - LICENSE

  nextflow_config:
    - manifest.name
    - manifest.homePage
    - validation.help.beforeText
    - validation.help.afterText
    - validation.summary.beforeText
    - validation.summary.afterText
    - config_defaults:
        - params.exomiser_analysis_wes # projectDir variable not rendered is causing mismatch with nextflow.config
        - params.exomiser_analysis_wgs  # projectDir variable not rendered is causing mismatch with nextflow.config

  multiqc_config: false

  files_exist:
    - assets/email_template.html
    - assets/email_template.txt
    - assets/multiqc_config.yml
    - assets/nf-core-cnv-post-processing_logo_light.png
    - assets/sendmail_template.txt
    - CODE_OF_CONDUCT.md
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - docs/images/nf-core-cnv-post-processing_logo_light.png
    - docs/images/nf-core-cnv-post-processing_logo_dark.png
    - .github/.dockstore.yml
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/ISSUE_TEMPLATE/feature_request.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - .github/workflows/branch.yml
    - .github/workflows/linting_comment.yml
    - ro-crate-metadata.json

  readme:
    - nextflow_badge

  actions_ci: false
  pipeline_name_conventions: false

template:
  org: Ferlab-Ste-Justine
  name: cnv-post-processing
  description: Nextflow pipeline dedicated to the post-processing of Copy Number Variants
    (CNVs).
  author: "Lysiane Bouchard, Georgette Femerling, F\xE9lix-Antoine Le Sieur, David\
    \ Morais"
  version: 1.0.0dev
  force: true
  outdir: .
  skip_features:
    - igenomes
    - github_badges
    - gitpod
    - codespaces
    - multiqc
    - fastqc
    - email
    - adaptivecard
    - slackreport
    - seqera_platform
    - rocrate
    - vscode
  is_nfcore: false
