name: nf-core CI
# This workflow runs the pipeline with the minimal test dataset to check that it completes without any syntax errors
on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

env:
  NXF_ANSI_LOG: false

concurrency:
  group:
    "${{ github.workflow }}-${{ github.event.pull_request.number || github.ref
    }}"
  cancel-in-progress: true

jobs:
  test:
    name:
      "Run pipeline with test data (${{ matrix.NXF_VER }} | ${{ matrix.test_name
      }} | ${{ matrix.profile }})"
    # Only run on push if this is the nf-core dev branch (merged PRs)
    if:
      "${{ github.event_name != 'push' || (github.event_name == 'push' && github.repository
      == 'Ferlab-Ste-Justine/cnv-post-processing') }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        NXF_VER:
          - 24.10.5
          - 23.10.1
          - latest-stable
        profile:
          - "docker"
        test_name:
          - "test"

    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Nextflow
        uses: nf-core/setup-nextflow@v2
        with:
          version: "${{ matrix.NXF_VER }}"

      - name: Clean up Disk space
        uses: jlumbroso/free-disk-space@v1.3.1

      - name:
          "Run pipeline with test data ${{ matrix.NXF_VER }} | ${{ matrix.test_name
          }} | ${{ matrix.profile }}"
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile ${{ matrix.test_name }},${{ matrix.profile }} --outdir ./results
